VC-client/VC-client/Controllers/LkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VC_client.Models;

namespace VC_client.Controllers
{
    [OptionalAuthorize]
    public class LkController : Controller
    {
        // GET: Lk
        public ActionResult Index()
        {
            try
            {
                return View(new LkEditModel(LkApi.GetUserInfo()));
            }
            catch (WebException ex)
            {
                return RedirectToAction("Login", "Account");
            } 

        }

        // GET: Lk/Edit/5
        public ActionResult Edit()
        {
            try
            {
                return View(new LkEditModel(LkApi.GetUserInfo()));
            }
            catch (WebException ex)
            {
                var r = (HttpWebResponse)ex.Response;
                return new HttpStatusCodeResult((HttpStatusCode)r.StatusCode,
                                   ex.Message);
            }
        }

        // POST: Lk/Edit/5
        [HttpPost]
        public ActionResult Edit(string Id, LkModels collection)
        {
            try
            {
                // TODO: Add update logic here
                var d = LkApi.SaveProfile(collection);
                return Json(new { res = "ok"});
            }
            catch (WebException ex)
            {
                var r = (HttpWebResponse)ex.Response;
                return new HttpStatusCodeResult((HttpStatusCode)r.StatusCode,
                                   ex.Message);
            }
        }

        // POST: Lk/Edit/5
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordBindingModel model)
        {
            try
            {
                // TODO: Add update logic here
                LkApi.ChangePassword(model);
                return Json(new { res = "ok" }, JsonRequestBehavior.AllowGet);
            }
            catch (WebException ex)
            {
                var r = (HttpWebResponse)ex.Response;
                return Json(new { error = "error", code = r.StatusCode, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult AddPhoto(HttpPostedFileBase inputFile)
        {

            if (inputFile == null)
                return Json(new { res = "ok", message = "Отсутствует фотография"});
            try
            {
                BinaryReader sr = new BinaryReader(inputFile.InputStream);
                var model = new LkModels();
                model.Photo = Convert.ToBase64String(sr.ReadBytes(inputFile.ContentLength));
                model.PhotoType = inputFile.ContentType;
                
                LkApi.SaveProfile(model);

            }
            catch (Exception ex)
            {
                return Json( new { res = "error", message = ex.Message });
            }

            return Json(new { res = "ok"});
        }
    }
}

VC-client/VC-client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="body-background">
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/common-site")
    @RenderSection("scripts", required: false)
    <footer class="footer hidden-xs">
        <div class="commonFooter">
            <div class="firstColFooter">
                <span class="footerText">© 2018 Credit Line</span>
            </div>
            <div class="otherColFooter">
                <span class="footerTitle">Телефон техподдержки КО</span><br>
                <span class="footerText">+7 (000) 000 00 00</span>
            </div>
            <div class="otherColFooter">
                <span class="footerTitle">Телефон Банка</span><br>
                <span class="footerText">+7 (000) 000 00 00</span>
            </div>
            <div class="otherColFooter">
                <span class="footerTitle">Email для связи</span><br>
                <span class="footerText">contact@email.com</span>
            </div>
        </div>
    </footer>

    <div class="modal fade" id="modalAlert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 999999999">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="word-wrap: break-word;" id="modalAlertBody">
                </div>
                <div class="modal-footer" style="border-top: 0px; text-align:center">
                    <button type="button" class="btn btn-success" data-dismiss="modal" style="min-width:190px">Закрыть</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-confirm" data-backdrop="static" style="z-index: 999999999">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body"></div>
                <div class="modal-footer" style="border-top: 0px; text-align:center">
                    <button type="button" class="btn btn-success confirm-ok" style="min-width:190px">Ок</button>
                    <button type="button" class="btn btn-warning confirm-cancel" style="min-width:190px">Отмена</button>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalSuccessPassword" data-backdrop="static">
        <div class="modal-dialog successPassword">
            <div class="modal-content">
                <div class="modal-body ">Данные успешно изменены</div>
            </div>
        </div>
    </div>

    <div class="showLkBack hidden" id="modalShowInfo">
        <div class="row" style="height:100%; margin-right: -2px">
            <div class="col-xs-12 col-md-5 col-md-offset-7 showLk">
                <div class="row" style="margin-top:20px">
                    <div class="col-xs-12 col-md-5" style="padding-right:5px">
                        <img src="~/Images/noavatar.png" alt="..." class="img-circle" height="80" />
                    </div>
                    <div class="col-xs-12 col-md-7" style="padding-top: 10px; padding-right: 5px; padding-left:5px">
                        <span class="valueShow">@Model.Fio</span>
                    </div>
                </div>
                <dl>
                    <dd class="titleShow">Телефон</dd>
                    <dt class="valueShow">@Model.PhoneNumber</dt>
                    <dd class="titleShow">Email</dd>
                    <dt class="valueShow">@Model.Email</dt>
                    <dd class="titleShow">Адрес регистрации</dd>
                    <dt class="valueShow">@Model.RegionRegistration</dt>
                </dl>
            </div>
        </div>
    </div>

    <div class="modal fade" id="changePassword" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-6 col-xs-offset-3 text-center">
                            <form id="changePasswordForm">
                                <div class="form-group">
                                    <label for="OldPassword">Старый пароль</label>
                                    <input type="password" id="OldPassword" name="OldPassword" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="OldPassword">Новый пароль</label>
                                    <input type="password" id="NewPassword" name="NewPassword" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="OldPassword">Подтверждение пароля</label>
                                    <input type="password" id="ConfirmPassword" name="ConfirmPassword" class="form-control" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="border-top: 0px; text-align:center">
                    <button type="button" class="btn btn-success" style="min-width:190px" id="changePasswordBtn">Изменить</button>
                    <button type="button" class="btn btn-warning" style="min-width:190px" data-dismiss="modal">Отмена</button>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalSigning" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="word-wrap: break-word;" id="modalSigningBody">
                    <p>Подписывая документ, соглашаюсь с тем, что мной прочитаны все документы, входящие в пакет</p>
                    <div class="row">
                        <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-2" style="margin-top: 10px">
                            <input type="text" id="sendCode" class="form-control" />
                        </div>
                        <div class="col-xs-6 col-xs-offset-2 col-md-6 col-md-offset-0" style="margin-top: 10px">
                            <button class="btn btn-success btn-success-sm" style="min-width: 190px; height:34px" id="sendCodeBtn">Выслать код</button>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 5px">
                        <div class="col-xs-12 col-md-8 col-md-offset-4 col-md-offset-0">
                            <span id="confirmTimeout" style="display:none; color:red">До отправки нового кода осталось: 30 сек</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-6">
                            <button type="button" class="btn btn-success btn-success-sm" style="min-width: 210px; height: auto" id="sendSigning">Подписать</button>
                        </div>
                        <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-6">
                            <button type="button" class="btn btn-warning btn-warning-sm" style="min-width: 210px; height: auto" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="loadPhotoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="word-wrap: break-word;" id="loadPhotoModalBody">
                    <p>Фотография должна быть не более 300 dpi. Размер не более 5 Мб</p>
                    @using (Html.BeginForm("AddPhoto", "Lk", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadPhotoForm" }))
                    {
                        <div class="form-group">
                            <label for="inputFile">Файл CSV</label>
                            <input type="file" id="inputPhoto" name="inputPhoto" accept="image/*"  data-toggle="tooltip" data-placement="right" title="Выберите файл">
                            <p class="help-block">Выберите фотографию</p>
                        </div>
                    }
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-6">
                            <button type="button" class="btn btn-success btn-success-sm" style="min-width: 210px; height: auto" id="loadPhotoBtn">Загрузить</button>
                        </div>
                        <div class="col-xs-6 col-xs-offset-3 col-md-offset-0 col-md-6">
                            <button type="button" class="btn btn-warning btn-warning-sm" style="min-width: 210px; height: auto" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

VC-client/VC-client/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</head>
<body class="body-background">

    <div class="body-content">
        @RenderBody()
    </div>


    <footer class="footer hidden-xs">
        <div class="loginFooter">
            <div class="loginFooterFormDiv">
                <span class="footerText">© 2018 Credit Line</span>
            </div>
            <div class="loginFooterFormDiv">
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerTitle">Телефон техподдержки КО</span>
                    </div>
                </div>
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerText">+7 (000) 000 00 00</span>
                    </div>
                </div>
            </div>
            <div class="loginFooterFormDiv">
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerTitle">Телефон Банка</span>
                    </div>
                </div>
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerText">+7 (000) 000 00 00</span>
                    </div>
                </div>
            </div>
            <div class="loginFooterFormDiv">
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerTitle">Email для связи</span>
                    </div>
                </div>
                <div class="row rowNoMargin">
                    <div class="col-xs-12 colxsnopading">
                        <span class="footerText">contact@email.com</span>
                    </div>
                </div>
            </div>

        </div>
    </footer>
</body>
</html>